apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-zjfp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-zjfp
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-zjfp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-zjfp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-zjfp
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-uxmt-tenant/status-quarkus-io/statusquarkusio-zjfp@sha256:b23abf5a9b2036225249dfacea26399f1594d7ec1c1875e7a80790cba2877ed3
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
